feat : join link api
arkavidia-hmif/arkavidia-backend-9.0 pull request #20
Opened 2024-12-16 10:19 UTC by Fakhripm

belom testing :V

2024-12-26 04:45 UTC, ValentinoTriadi requested changes

2024-12-26 04:45 UTC, ValentinoTriadi commented on src/routes/team.route.ts
ini kayaknya kalo di tes bakal eror deh, soalnya pathnya gaada placeholder buat param nya. jadi boleh tolong di tes dlu ga yaa?

2024-12-26 12:05 UTC, Fakhripm commented on src/routes/team.route.ts
okeh valen

2025-01-11 11:00 UTC, Fakhripm commented
<img width="1013" alt="image" src="https://github.com/user-attachments/assets/79ed0cd8-c31d-4a5f-a281-3d8a78ce57b1" />

doakan :D

2025-01-11 11:54 UTC, ValentinoTriadi approved these changes

2025-01-11 11:54 UTC, merged